### ISSUE TITLE
Indent guide is being blocked

### ISSUE THREAD

**Issue by ZYinMD** [usernamehw/vscode-highlight-logical-line#1]
Hi, awesome extension!!

One issue: the line highlight is now blocking the indent guide. In comparison, the original highlight without the extension doesn't block the indent guide. 

- The quickest fix may be switch back to the original native rendering when Word Wrap is turned off.
- The second step may be to use the native rendering on the short lines that are not wrapped, even when Word Wrap is turned on. This way the impact is minimized. 
- The ultimate fix should be always show indent guide at any time. This is the behavior of Sublime Text.

**Comment by usernamehw** [comment]
Thanks for the feedback!

* Yeah, I'm going to watch for `"editor.wordWrap": "on",` setting. If it's set to `off` - then this extension should not be activated (Only there's this "in memory" event <kbd>Alt</kbd>+<kbd>Z</kbd> that I don't think it's possible to watch)
* > The second step may be to use the native rendering on the short lines that are not wrapped, even when Word Wrap is turned on. This way the impact is minimized.

The rendering of indent guides would be inconsistent (people will notice that much faster).

* Thinking about simply using transparent bg (The only one that I tested tbh) - it just works:
![indent](https://user-images.githubusercontent.com/9638156/48219616-03a0ae00-e39e-11e8-8e0d-09c204023687.gif)
