### ISSUE TITLE
The color of the selected text is not displayed when highlighting enabled

### ISSUE THREAD

**Issue by ExceptionGit** [usernamehw/vscode-highlight-logical-line#2]
Write **one** line and try to select text (shift+right shift+left) , i see only `#424242`. If there are two lines, then the first line selected shows the color `#ff0000`, and the last line does not show the color.

```json
{
    "workbench.colorCustomizations": {
        "highlightLogicalLine.background": "#424242",
        "editor.lineHighlightBackground": "#424242",

        "editor.selectionHighlight": "#ff0000",
        "editor.selectionBackground": "#ff0000",
        "editor.selectionHighlightBackground": "#ff0000",
        "editor.selectionForeground": "#ff0000",
        "editor.selectionHighlightBorder": "#ff0000",
        "editor.inactiveSelectionBackground": "#ff0000",
        "editorOverviewRuler.selectionHighlightForeground": "#ff0000",
    },
    "editor.renderLineHighlight": "gutter",
    "editor.wordWrap": "on",
}
```

**Comment by usernamehw** [comment]
Can you try to use transparency?
```js
"highlightLogicalLine.background": "#424242aa",
```

 Also, if you want, I can disable line highlighting if the editor has selection.

**Comment by ExceptionGit** [comment]
WOW, transparency works. Thanks for your help!


>Also, if you want, I can disable line highlighting if the editor has selection.

No-no, perhaps you will add additional information about it to the "Recommended Settings" or automatically change the transparency if it is not set.
